# SPDX-License-Identifier: Apache-2.0
version: '2.1'

networks:
  exchangeNtw:
    external:
      name: exchangeNtw

services:
  explorerdb.banksco.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.banksco.com
    hostname: explorerdb.banksco.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - exchangeNtw

  explorer.banksco.com:
    image: hyperledger/explorer:latest
    container_name: explorer.banksco.com
    hostname: explorer.banksco.com
    environment:
      - DATABASE_HOST=explorerdb.banksco.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile.json:/opt/explorer/app/platform/fabric/connection-profile.json
      - ../ExchangeNetwork/CCLifeCycleHLFv2/crypto-config:/tmp/crypto
      # - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.banksco.com:
        condition: service_healthy
    networks:
      - exchangeNtw